<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time at WorkNot Punched In0h 0m TodayTh_23ad64</name>
   <tag></tag>
   <elementGuidId>22ed48e0-79f6-497c-b234-45ef8afe6a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b569e1e5-8c0f-4b86-8f0f-6b4699049af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>1e5946b7-3e6d-440c-b115-e2af0b7300a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time at WorkNot Punched In0h 0m TodayThis WeekNov 07 - Nov 130h 0m My ActionsNo Pending Actions to PerformQuick LaunchNot AvailableEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitUnassignedEmployee Distribution by LocationUnassigned</value>
      <webElementGuid>a756ffc6-7602-4780-b569-a0e09a22e291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>51a294ab-f7b5-4ade-9ae0-c5a0bb73b62e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>9f32c77b-fcc6-4cc1-a49b-f6c0c25a7ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>322f83ff-01ce-43a8-bd0b-b859e2522cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Time at WorkNot Punched In0h 0m TodayThis WeekNov 07 - Nov 130h 0m My ActionsNo Pending Actions to PerformQuick LaunchNot AvailableEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitUnassignedEmployee Distribution by LocationUnassigned' or . = 'Time at WorkNot Punched In0h 0m TodayThis WeekNov 07 - Nov 130h 0m My ActionsNo Pending Actions to PerformQuick LaunchNot AvailableEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitUnassignedEmployee Distribution by LocationUnassigned')]</value>
      <webElementGuid>b22feeeb-a59e-43f1-bb9a-1f399de6169c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
